debian/platform-modules-dx010.install, dx010/scripts/port-mode.sh
Add port-mode switch script to device package.
NOTE: This require the add-port-mode-switch branch in sonic-buildimage.
=> Add port-mode switch script to support 100G 50G 10G_50G qsfp modes.

dx010/modules/dx010_cpld.c
Fix the eeprom word read data incorrect endian.
=> Fix incorrect endian in eeprom read word data.

debian/platform-modules-fishbone32.init, debian/platform-modules-fishbone48.init, debian/platform-modules-phalanx.init, fishbone32/cfg/fishbone32-modules.conf, fishbone32/modules/Makefile, fishbone32/modules/dimm-bus.c, fishbone32/modules/dimm-bus.h, fishbone32/modules/i2c-imc.c, fishbone48/cfg/fishbone48-modules.conf, fishbone48/modules/Makefile, fishbone48/modules/dimm-bus.c, fishbone48/modules/dimm-bus.h, fishbone48/modules/i2c-imc.c, phalanx/cfg/phalanx-modules.conf, phalanx/modules/Makefile, phalanx/modules/dimm-bus.c, phalanx/modules/dimm-bus.h, phalanx/modules/i2c-imc.c
Add Intel iMC SMbus driver for reading TSoD value from DIMM.
---
This driver is dangerous, please not use with care.
=> [Phalanx/Fishbones] Add iMC SMBus for DIMM SPD and TSoD access.

debian/platform-modules-fishbone32.init, debian/platform-modules-fishbone48.init, debian/platform-modules-phalanx.init
Fix platform init script loading failed.  
Add option **allow_unsafe_access=1** in i2c_imc module loading.
=> [Phalanx/Fishbones] Fix bug loading i2c_imc in init scritp.

fishbone32/modules/i2c-imc.c, fishbone48/modules/i2c-imc.c, phalanx/modules/i2c-imc.c
Remove the seconds channel, always return zero when do smbus_xfer on it.
=> [Fishbones/Phalanx] Disable imc bus create for 2nd channel.

fishbone32/modules/switchboard_fpga.c, fishbone48/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
Some I2C busses always occupied by BMC, these busses should not be accessed by SONiC.
In diagnostic sometimes they need to be accessed.
To do this add kernel module option to enable unsafe access to I2C busses when needed.
=> Remove i2c devices overlap bmc

fishbone48/modules/switchboard_fpga.c
There is an issue when pca9548 switch is jamming two or more channel together. 
This issue cause bogus value read from EEROM.
Also, another issue is arbitration lost from FPGA I2C core.
When reading SFP EEPROM with clock stretching, sometimes the I2C core report arbitration lost and stop the transaction.
As a workaround on this, we add the delay to cover the slave clock stretching period.  This will prevent the read failed, but also suffer the I2C performance.
=> Improve i2c switch set issue

fishbone48/modules/switchboard_fpga.c
Remove delay workaround in smbus_xfer function on Fishbone48.
=> [Fishbone48] Remove delay workaround in i2c smbus_xfer

tools/read_optic_temp.py, tools/sync_bmc/sync_bmc.py
1.Use python to open sysfs EEPROM directly instead of external call of i2ctool.
2.This will fix the i2c access conclict when sync_bcm and sfputil
accessing EEPROM at same time.
=> [Alibaba] Improve front panel EEPROM access in sync_bmc.

debian/platform-modules-fishbone32.init, debian/platform-modules-fishbone48.init, debian/platform-modules-phalanx.init
*Add mc24lc64t driver probe before instantiating new i2c device on Fishbones48, Fishbone32, and Phalanx platform.
Issue #30 
**Need to build and test before accept merge.**
=> [platform/braodcom] Alibaba - Add mc24lc64t in platform init script.

fishbone32/modules/switchboard_fpga.c, fishbone48/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
This fix the bug when PCI device added and the kernel auto probe was enabled.
- The driver part will be removed when module probe fails.
=> Alibaba - fix switchboard driver auto probe fail bug.

debian/platform-modules-fishbone32.install, debian/platform-modules-fishbone32.postinst, debian/platform-modules-fishbone48.install, debian/platform-modules-fishbone48.postinst, debian/platform-modules-phalanx.install, debian/platform-modules-phalanx.postinst, fishbone32/systemd/platform-modules-fishbone32.service, fishbone48/systemd/platform-modules-fishbone48.service, phalanx/systemd/platform-modules-phalanx.service
**What I did?**
Fix the platform module does not load when OS start.
**How I did it?**
Add the systemd unit file to platform-module-cel package and enable the service in post install script.
**How to verify?**
After the system boot up, the platform module must load autometically.
=> [platform/broadcom] Use systemd to load platform services

fishbone32/modules/switchboard_fpga.c, fishbone48/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
*Updates on Foshbone32, Fishbone48, and Phalanx.
=> [Alibaba] - Upadate FPGA I2C bus frequency to 98Khz for all platforms

fishbone32/modules/switchboard_fpga.c, fishbone48/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
__What I did?__
Fix the fault alert kernel message, when rescanning FPGA device.
__How I did?__
Update the device driver probe sequence after kernel module added. This will fix the fault alert message about FPGA device not found in the debug message.
=> [phalanx/fishbone] Fix fault alert message when insert kernel module

fishbone32/modules/switchboard_fpga.c, fishbone48/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
**- What I did**
Update the switchboard I2C access to recovery the optical module bus after bus stuck detected.
**- How I did it**
1. Add a condition to detect the bus stuck in I2C transfer function.
2. When trying to access the device and failed with `-EBUSY` check if the I2C switch on the bus can still be reached, if not decides as a bus stuck.
3. Reset the switch to disconnect the stuck channel from the upstream bus.
4. Log the error message in the kernel log. (dmesg)
**- How to verify it**
1. Simulate the bus stuck by fly-wire the SDA of first front panel port to low, then run `sfputil show eeprom` on a port, the bus stuck must not affect other port EEPROM access.
**- Description for the changelog**
- Fishbone/Phalanx add optical module I2C bus resilience.
**- A picture of a cute …
=> Ali phalanx fishbone 201811 add om bus recovery

fishbone32/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
The change will add the following changes to i2c adapter driver to fix the write 0xFF issue in the optical module EEPROM. 
__Modules:__ I2C adapter driver
__Platforms:__ Phalanx, Fishbone32
__Changes__:
1. Apply clock stretching workaround.
2. Add Interrupt acknowledge (IACK) back when issue command to CMD register.
1. Add 8 clocks delay before start polling TIP bit in STATUS register.
=> [Phalanx/Fishbone32] Add workaround for EEPROM for write FF issue

fishbone32/modules/switchboard_fpga.c, fishbone48/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
This change fix incorrect port xcvr statuses return from sysfs. Sometimes the port read as not present while the port is still plugged-in. Checking and found that there is a resource race condition in the sysfs driver. To fix this I add one mutex lock per shared resource to prevent the race condition.
**Platform:** Fishbone32, Fishbone48, Phalanx
**Changes:**
1. Add a resource lock to protect switchboard CPLD from a resource race condition. This will fix the random "EEPROM not detected" issue when the Optical module plugin. 
2. Fix one PCA9548 cannot be reset on each lien card. (Phalanx only)
JIRA: [CAFP-115](http://jira.cn-csh.celestica.com:8080/browse/CAFP-115)
=> [Phalanx/Fishbones][BSP] Fix port xcvr status race condition

debian/platform-modules-fishbone32.install, debian/platform-modules-fishbone32.postinst, debian/platform-modules-fishbone48.install, debian/platform-modules-fishbone48.postinst, debian/platform-modules-phalanx.install, debian/platform-modules-phalanx.postinst, tools/bmc_console_log/bmc-console-log, tools/bmc_console_log/bmc-console-log.service
Log the BMC serial console from _/dev/ttyS1_ and stream them to syslog.
Each log line has a timestamp and tagged with "bmc#console".
**NOTE:** This change **REQUIRED** new Baseboard CPLD with BMC console output mirroring feature. 
JIRA: [CAFP-98](http://jira.cn-csh.celestica.com:8080/browse/CAFP-98)
___
Output on Phalanx:
```
Linux sonic 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2015-12-19) x86_64
You are on
____   ___  _   _ _  ____
/ ___| / _ \| \ | (_)/ ___|
\___ \| | | |  \| | | |
___) | |_| | |\  | | |___
|____/ \___/|_| \_|_|\____|
-- Software for Open Networking in the Cloud --
Unauthorized access and/or use are prohibited.
All access and/or use are subject to monitoring.
Help:    http://azure.github.io/SONiC/
Last login: Sat Dec 17 20:37:26 2016
admin@sonic:~$ sudo -s …
```
=> [tools/bmc_console_log] Add BMC serial console logging service.

fishbone32/modules/switchboard_fpga.c, fishbone48/modules/switchboard_fpga.c, phalanx/modules/switchboard_fpga.c
1. The candidate of #47 with minimal changes.
The _NULL_ pointer condition check is added to i2c-access functions.  If _NULL_ is found, a function will not perform I2c operation and exit with **[ESHUTDOWN](https://www.kernel.org/doc/Documentation/i2c/fault-codes)** status indicates that the adapter is not ready to use (suspended).
Changes applied to followings:
* i2c_wait_stop()
* i2c_wait_ack()
* smbus_access()
* fpga_i2c_access()
2. Add the fix for 100 cycle module load/unload cause kernel panic.
The fix removes duplicate class unregister statement in `fpgafw_exit()` function.
JIARA: [CAFP-139](http://jira.cn-csh.celestica.com:8080/browse/CAFP-139)
**NOTE:** The module versions have -rc2 suffix, it will be removed if this candidate is selected.
=> [Fishbones/Phalanx] Fix kernel panic while removing switchboard_fpga 

tools/bmcutil/bmc-exec
Add confirmation y/n for bmc power command
Test log: [bmc-exec_0309.log](https://github.com/celestica-Inc/sonic-platform-modules-cel/files/4305644/bmc-exec_0309.log)
=> [tools/bmc-exec]: Add confirmation support for power cycle command
